### ISSUE TITLE
Demo site

### ISSUE THREAD

**Issue by petersmythe** [sasakiassociates/paint-the-map#1]
Nice presentation at FOSS4G 2021, Ken.  It would be great to also provide a demo site

**Comment by gouldingken** [comment]
Thanks for the suggestion. I'll try to put one up today. Thanks for attending the FOSS4G presentation.

**Comment by gouldingken** [comment]
Here's a link (also added to readme) https://maps.sasaki.com/paint-the-map/examples/paint-tool/
